# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy dependency file and install
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy app code
COPY . .

# Run the application
CMD ["python", "app.py"]
